language: node_js
node_js:
  - "8"

before_script:
  - 'yarn build'

after_success:
  - 'npx codecov'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master